apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-tenant-project-rbac-app-of-apps
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/noahburrell0/akuity-examples.git
    targetRevision: main
    path: multi-tenant-project-rbac/argocd
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd
