apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-samplec
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/noahburrell0/argocd-project-samplec.git
    targetRevision: main
    path: apps
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd
