apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-noahs-project
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/noahburrell0/argocd-project-noahs-project.git
    targetRevision: main
    path: apps
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd
