apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-tst2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/noahburrell0/argocd-project-tst2.git
    targetRevision: main
    path: apps
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd
