apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-kishore
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: project-quickstart-demo
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/dhpup/argocd-project-kishore.git
    targetRevision: main
    path: apps
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd
