apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-team-cat
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: project-onboarding
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/dhpup/argocd-project-team-cat.git
    targetRevision: main
    path: apps
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd
