apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp
  target:
    name: example-secret
    creationPolicy: Owner
  data:
  - secretKey: LICENSE_KEY
    remoteRef:
      key: LICENSE_KEY