apiVersion: v1
kind: Secret
metadata:
  name: default.service-account-token
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agent
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets
    verbs:
      - list
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets/status
    verbs:
      - patch
  - apiGroups:
      - external-secrets.io
    resources:
      - externalsecrets
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agent
subjects:
  - kind: ServiceAccount
    name: default

---

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: get-color-validation
  annotations:
     argocd.argoproj.io/hook: PostSync
spec:
  entrypoint: main
  serviceAccountName: default
  ttlStrategy:
    secondsAfterCompletion: 100
  templates:
  - name: Create color secret
    resource:
      action:
      setOwnerReference: true
      successCondition: status.conditions[0].status == True
      manifest: |
        apiVersion: external-secrets.io/v1beta1
        kind: ExternalSecret
        metadata:
          name: color-test
        spec:
          refreshInterval: 5s
          secretStoreRef:
            kind: ClusterSecretStore
            name: gcp
          target:
            name: color-test
            creationPolicy: Owner
          data:
          - secretKey: COLOR
            remoteRef:
              key: COLOR