apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-secretmanager-sa-key
            namespace: external-secrets
            key: secret-access-credentials
      projectID: akuity-training