apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- install.yaml
- default-clusterrole.yaml

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --auth-mode=server
  target:
    kind: Deployment
    name: argo-server
- patch: |-
    - op: add
      path: /spec/ports/0/nodePort
      value: 2746
  target:
    kind: Service
    name: argo-server