apiVersion: apps/v1
kind: Deployment
metadata:
  name: postsync-validation-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postsync
  template:
    metadata:
      labels:
        app: postsync
    spec:
      containers:
      - name: canary-demo
        image: argoproj/rollouts-demo:green
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
        env:
        - name: ERROR_RATE
          value: '0'

---

apiVersion: v1
kind: Service
metadata:
  name: postsync-validation-svc
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: postsync

---

apiVersion: batch/v1
kind: Job
metadata:
  name: postsync-validation-hook
  annotations:
     argocd.argoproj.io/hook: PostSync
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: ubuntu
        image: ubuntu:20.04
        command:
        - /bin/bash
        - -c
        - |
          set -x
          apt update && apt install -y curl
          curl -f http://postsync-validation-svc/color
          if [ $? -eq 0 ]
          then
            echo "SUCCESS"
            exit 0
          else
            echo "FAILURE"
            exit 1
          fi

---

apiVersion: batch/v1
kind: Job
metadata:
  name: syncfail-validation-hook
  annotations:
     argocd.argoproj.io/hook: SyncFail
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: ubuntu
        image: ubuntu:20.04
        command:
        - /bin/bash
        - -c
        - |
          echo "Oh no! It looks like the sync failed. I'm going to do something about that"