apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-bastian
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
    namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false