apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-and-app-parent
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: project-and-app/argocd
    repoURL: 'https://github.com/dhpup/akuity-examples.git'
    targetRevision: main
  syncPolicy:
    automated: {}