apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-webhook-source
spec:
  service:
    ports:
      - port: 30004
        targetPort: 30004
  webhook:
    github:
      port: "30004"
      endpoint: /github
      method: POST
---
apiVersion: v1
kind: Service
metadata:
  name: github-webhook-eventsource
spec:
  ports:
  - port: 30004
    protocol: TCP
    targetPort: 30004
    nodePort: 30004
  selector:
    eventsource-name: github-webhook-source
  type: NodePort