apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-upgrader
  namespace: argocd
spec:
  project: workflows-infrastructure-demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    path: demos/workflows-infrastructure/configs/cluster-upgrader
    repoURL: https://github.com/dhpup/akuity-examples.git
    targetRevision: main
  destination:
    name: mac1
    namespace: cluster-upgrader
