apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: demo-workflows-infrastructure
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.9
  - path: demos/workflows-infrastructure/configs/external-secrets
    repoURL: https://github.com/dhpup/akuity-examples.git
    targetRevision: main
  destination:
    name: demo1
    namespace: external-secrets
