apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: postsync-workflow-validation
spec:
  generators:
  - list:
      elements:
      - name: success
        errors: '0'
        nodePort: '30001'
      - name: fail
        errors: '1'
        nodePort: '30002'
  template:
    metadata:
      name: 'postsync-workflow-validation-{{name}}'
      namespace: argocd
      labels:
        notifications: "true"
    spec:
      project: workflows-infrastructure-demo
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
      source:
        path: demos/workflows-infrastructure/configs/postsync-workflow-validation
        repoURL: https://github.com/dhpup/akuity-examples.git
        targetRevision: main
        kustomize:
          patches:
            - target:
                kind: Deployment
                name: postsync-validation-deploy
              patch: |-
                - op: add
                  path: /spec/template/spec/containers/0/env/0/name
                  value: ERROR_RATE
                - op: add
                  path: /spec/template/spec/containers/0/env/0/value
                  value: '{{errors}}'
            - target:
                kind: Service
                name: postsync-validation-svc
              patch: |-
                - op: add
                  path: /spec/ports/0/nodePort
                  value: {{nodePort}}
      destination:
        name: mac1
        namespace: 'postsync-workflow-validation-{{name}}'
