apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: demo-workflows-infrastructure
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - chart: reloader
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 1.0.16
  destination:
    name: demo1
    namespace: external-secrets
