apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-quickstart
spec:
  project: project-onboarding
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  source:
    repoURL: https://github.com/dhpup/akuity-examples.git
    targetRevision: main
    path: project-quickstart/argocd
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd
