apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-b
  namespace: argocd
spec:
  project: project-b
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://github.com/akuity/guestbook-deploy.git
    targetRevision: HEAD
    path: env/dev
  destination:
    name: demo1
    namespace: guestbook-b
