apiVersion: apps/v1
kind: Deployment
metadata:
  name: postsync-validation-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postsync
  template:
    metadata:
      labels:
        app: postsync
    spec:
      containers:
      - name: canary-demo
        image: argoproj/rollouts-demo:green
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
        env:
        - name: ERROR_RATE
          value: '0'

---

apiVersion: v1
kind: Service
metadata:
  name: postsync-validation-svc
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: postsync

---

apiVersion: v1
kind: Secret
metadata:
  name: default.service-account-token
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agent
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets
    verbs:
      - list
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets/status
    verbs:
      - patch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agent
subjects:
  - kind: ServiceAccount
    name: default

---

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: get-color-validation
  annotations:
     argocd.argoproj.io/hook: PostSync
spec:
  entrypoint: main
  serviceAccountName: default
  templates:
    - name: main
      steps:
        - - name: get-color
            template: http
            arguments:
              parameters: [{name: url, value: "http://postsync-validation-svc/color"}]
    - name: http
      inputs:
        parameters:
          - name: url
      http:
        url: "{{inputs.parameters.url}}"
        method: "GET"
        successConfidition: "response.statusCode == 200"