apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postsync-validation-deploy-cm
spec:
  refreshInterval: '0'
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp
  target:
    name: postsync-validation-deploy-cm
    creationPolicy: Owner
  data:
  - secretKey: COLOR
    remoteRef:
      key: COLOR

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postsync-validation-deploy
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postsync
  template:
    metadata:
      labels:
        app: postsync
    spec:
      containers:
      - name: canary-demo
        image: argoproj/rollouts-demo:green
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
        env:
        - name: ERROR_RATE
          value: '0'
        envFrom:
        - secretRef:
            name: postsync-validation-deploy-cm

---

apiVersion: v1
kind: Service
metadata:
  name: postsync-validation-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: postsync

---

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: check-errors
  annotations:
     argocd.argoproj.io/hook: PostSync
spec:
  entrypoint: main
  serviceAccountName: default
  ttlStrategy:
    secondsAfterCompletion: 300
  templates:
    - name: main
      steps:
        - - name: get-color
            template: http
            arguments:
              parameters: [{name: url, value: "http://postsync-validation-svc/color"}]
    - name: http
      inputs:
        parameters:
          - name: url
      http:
        url: "{{inputs.parameters.url}}"
        method: "GET"
        successConfidition: "response.statusCode == 200"

---

apiVersion: batch/v1
kind: Job
metadata:
  name: syncfail-validation-hook
  annotations:
     argocd.argoproj.io/hook: SyncFail
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: ubuntu
        image: ubuntu:20.04
        command:
        - /bin/bash
        - -c
        - |
          echo "Oh no! It looks like the sync failed. I'm going to do something about that"