apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-waves-and-hooks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dhpup/akuity-examples.git
    targetRevision: main
    path: sync-waves-and-hooks/manifests
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: sync-waves-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
