apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: REPLACE_ME
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: REPLACE_ME
    targetRevision: main
    path: apps
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd
