apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: REPLACE_ME_PROJECT
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
    namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false