apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-git-files-generator
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/dhpup/akuity-examples.git
    targetRevision: main
    path: git-files-generator/argocd
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd
