name: Create New Project
on:
  workflow_dispatch:
    inputs:
      projectName:
        description: The name of the new project to create.
        required: true
        type: string
      templateRepo:
        description: The template repository to clone from.
        required: true
        type: string
        default: noahburrell0/project-template
jobs:
  clone-template-repo:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - run: gh repo create argocd-project-${{ inputs.projectName }} --template ${{ inputs.templateRepo }} --clone --public
      - run: ls -al