name: Create New Project
on:
  workflow_dispatch:
    inputs:
      projectName:
        description: The name of the new project to create.
        required: true
        type: string
jobs:
  clone-template-repo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.projectName }}"